{
 "title": "Vehicle Overview",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "100ms",
 "templating": {
  "list": [
   { "name": "data_source", "query": "WFR2025,ourCar" }
  ]
 },
 "panels": [
  {
   "title": "Inverter Phase Currents",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"INV_Diag_Ia\" or r[\"signalName\"] == \"INV_Diag_Ib\" or r[\"signalName\"] == \"INV_Diag_Ic\" or r[\"signalName\"] == \"INV_Diag_Id_cmd\" or r[\"signalName\"] == \"INV_Diag_Iq_cmd\" or r[\"signalName\"] == \"INV_Phase_A_Current\" or r[\"signalName\"] == \"INV_Phase_B_Current\" or r[\"signalName\"] == \"INV_Phase_C_Current\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "Torque & Motor Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"canBus\" and\r\n    r[\"_field\"] == \"sensorReading\" and\r\n    (\r\n      r[\"signalName\"] == \"VCU_INV_Torque_Command\" or\r\n      r[\"signalName\"] == \"INV_Torque_Feedback\" or\r\n      r[\"signalName\"] == \"INV_Torque_Capability\"\r\n    )\r\n  )\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    },
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"canBus\" and\r\n    r[\"_field\"] == \"sensorReading\" and\r\n    (\r\n      r[\"signalName\"] == \"INV_Motor_Speed\"\r\n    )\r\n  )\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    }
   ]
  },
  {
   "title": "Inverter Voltage and Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"INV_DC_Bus_Voltage\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    },
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"M167_Voltage_Info\" or r[\"messageName\"] == \"M176_Fast_Info\" or r[\"messageName\"] == \"M166_Current_Info\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"INV_DC_Bus_Current\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    }
   ]
  },
  {
   "title": "Brake Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"VCU_Front_Sensors_1\" or r[\"messageName\"] == \"VCU_Front_Sensors_2\" or r[\"messageName\"] == \"VCU_Front_Sensors_3\" or r[\"messageName\"] == \"VCU_Front_Sensors_4\" or r[\"messageName\"] == \"VCU_State_Info\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"A3\" or r[\"signalName\"] == \"A4\" or r[\"signalName\"] == \"Throttle\" or r[\"signalName\"] == \"A2\" or r[\"signalName\"] == \"A12\" or r[\"signalName\"]==\"A9\" or r[\"signalName\"]==\"A14\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    }
   ]
  },
  {
   "title": "Cell Temps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"TORCH_M1_T1\" or r[\"messageName\"] == \"TORCH_M1_T2\" or r[\"messageName\"] == \"TORCH_M1_T3\" or r[\"messageName\"] == \"TORCH_M1_T4\" or r[\"messageName\"] == \"TORCH_M1_T5\" or r[\"messageName\"] == \"TORCH_M2_T1\" or r[\"messageName\"] == \"TORCH_M2_T2\" or r[\"messageName\"] == \"TORCH_M2_T3\" or r[\"messageName\"] == \"TORCH_M2_T4\" or r[\"messageName\"] == \"TORCH_M2_T5\" or r[\"messageName\"] == \"TORCH_M3_T1\" or r[\"messageName\"] == \"TORCH_M3_T2\" or r[\"messageName\"] == \"TORCH_M3_T3\" or r[\"messageName\"] == \"TORCH_M3_T4\" or r[\"messageName\"] == \"TORCH_M3_T5\" or r[\"messageName\"] == \"TORCH_M4_T1\" or r[\"messageName\"] == \"TORCH_M4_T2\" or r[\"messageName\"] == \"TORCH_M4_T3\" or r[\"messageName\"] == \"TORCH_M4_T4\" or r[\"messageName\"] == \"TORCH_M4_T5\" or r[\"messageName\"] == \"TORCH_M5_T1\" or r[\"messageName\"] == \"TORCH_M5_T2\" or r[\"messageName\"] == \"TORCH_M5_T3\" or r[\"messageName\"] == \"TORCH_M5_T4\" or r[\"messageName\"] == \"TORCH_M5_T5\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => \r\n    r[\"messageName\"] == \"TORCH_M1_V1\" or r[\"messageName\"] == \"TORCH_M1_V2\" or r[\"messageName\"] == \"TORCH_M1_V3\" or r[\"messageName\"] == \"TORCH_M1_V4\" or r[\"messageName\"] == \"TORCH_M1_V5\" or\r\n    r[\"messageName\"] == \"TORCH_M2_V1\" or r[\"messageName\"] == \"TORCH_M2_V2\" or r[\"messageName\"] == \"TORCH_M2_V3\" or r[\"messageName\"] == \"TORCH_M2_V4\" or r[\"messageName\"] == \"TORCH_M2_V5\" or\r\n    r[\"messageName\"] == \"TORCH_M3_V1\" or r[\"messageName\"] == \"TORCH_M3_V2\" or r[\"messageName\"] == \"TORCH_M3_V3\" or r[\"messageName\"] == \"TORCH_M3_V4\" or r[\"messageName\"] == \"TORCH_M3_V5\" or\r\n    r[\"messageName\"] == \"TORCH_M4_V1\" or r[\"messageName\"] == \"TORCH_M4_V2\" or r[\"messageName\"] == \"TORCH_M4_V3\" or r[\"messageName\"] == \"TORCH_M4_V4\" or r[\"messageName\"] == \"TORCH_M4_V5\" or\r\n    r[\"messageName\"] == \"TORCH_M5_V1\" or r[\"messageName\"] == \"TORCH_M5_V2\" or r[\"messageName\"] == \"TORCH_M5_V3\" or r[\"messageName\"] == \"TORCH_M5_V4\" or r[\"messageName\"] == \"TORCH_M5_V5\"\r\n  )\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    }
   ]
  },
  {
   "title": "Pack Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"PackStatus\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"PackStatus\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    },
    {
     "query": "import \"internal/debug\"\r\nfrom(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"PackStatus\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"Fault\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value <= 1.0 then r._value\r\n              else if r._value <= 68.0 then 0.0\r\n              else if r._value >= 69.0 then (r._value - 68.0)\r\n              else debug.null(type: \"int\") // Sentinel value\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"signalName\"], valueColumn: \"_value\")\r\n  "
    }
   ]
  },
  {
   "title": "VCU State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"VCU_State_Info\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"State\")\r\n  |> aggregateWindow(every: 10ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n"
    }
   ]
  },
  {
   "title": "Inverter States",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"M170_Internal_States\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"INV_BMS_Torque_Limiting\" or r[\"signalName\"] == \"INV_Inverter_Enable_State\" or r[\"signalName\"] == \"INV_Inverter_Run_Mode\" or r[\"signalName\"] == \"INV_Inverter_State\" or r[\"signalName\"] == \"INV_Limit_Coolant_Derating\" or r[\"signalName\"] == \"INV_Limit_Hot_Spot\" or r[\"signalName\"] == \"INV_Limit_Max_Speed\" or r[\"signalName\"] == \"INV_Limit_Stall_Burst_Model\" or r[\"signalName\"] == \"INV_Low_Speed_Limiting\" or r[\"signalName\"] == \"INV_VSM_State\")\r\n  |> aggregateWindow(every: 100ms, fn: max)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    },
    {
     "query": "from(bucket: \"${data_source}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"VCU_INV_Inverter_Enable\")\r\n  |> aggregateWindow(every: 100ms, fn: max)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    }
   ]
  },
  {
   "title": "Inverter Temps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"M160_Temperature_Set_1\" or r[\"messageName\"] == \"M161_Temperature_Set_2\" or r[\"messageName\"] == \"M162_Temperature_Set_3\")\r\n  |> filter(fn: (r) => r[\"signalName\"] == \"INV_Control_Board_Temp\" or r[\"signalName\"] == \"INV_Coolant_Temp\" or r[\"signalName\"] == \"INV_Gate_Driver_Board_Temp\" or r[\"signalName\"] == \"INV_Hot_Spot_Temp\" or r[\"signalName\"] == \"INV_Module_A_Temp\" or r[\"signalName\"] == \"INV_Module_B_Temp\" or r[\"signalName\"] == \"INV_Module_C_Temp\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])"
    }
   ]
  },
  {
   "title": "Inverter Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "query": "from(bucket: \"${data_source}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"canBus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensorReading\")\r\n  |> filter(fn: (r) => r[\"messageName\"] == \"M171_Fault_Codes\")\r\n  |> aggregateWindow(every: 1s, fn: max)\r\n  |> keep(columns: [\"_time\", \"_value\", \"signalName\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"signalName\"], valueColumn: \"_value\")\r\n  \r\n"
    }
   ]
  }
 ]
}